[workspace]
resolver = "2"

members = [
    # GUI
    "gui/api",
    "gui/controller",
    "gui/definition",
    "gui/gui",
    "gui/render_balancer",
    "gui/render_core",

    # Compositor
    "compositor/compositor",
    "compositor/compositor_core",

    # Drivers
    "drivers/amd_driver",
    "drivers/intel_driver"
]

